-- Création de la table Utilisateurs
--CREATE DOMAIN RoleDomain AS VARCHAR(255) CHECK (VALUE IN ('USER', 'ADMIN'));
CREATE TABLE IF NOT EXISTS Utilisateur (
                             IdUtilisateur SERIAL PRIMARY KEY,
                             Nom VARCHAR(255),
                             Prenom VARCHAR(255),
                             DateNaissance DATE,
                             MotDePasseHache VARCHAR(255),
                             Email VARCHAR(255),
                             Adresse TEXT,
                             roleutilisateur VARCHAR(10) CHECK (VALUE IN ('USER', 'ADMIN'),
                             DateCreation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                             DerniereDateMAJ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                             Status VARCHAR(10) CHECK (VALUE IN ('ONLINE', 'OFFLINE')
);

-- Création de la table Devise
CREATE TABLE IF NOT EXISTS Devise (
    --IdDevise SERIAL PRIMARY KEY,
                        CodeDevise VARCHAR(3) PRIMARY KEY,
                        NomDevise VARCHAR(255)
);

-- Création de la table DemandeDevise
CREATE DOMAIN StatutDemande AS VARCHAR(255) CHECK (VALUE IN ('ENATTENTE', 'ENCOURS', 'ACCEPTER',
                                                             'PAYER',
                                                             'ANNULER',
                                                             'TERMINER'));
CREATE TABLE IF NOT EXISTS DemandeDevise (
                               IdDemande SERIAL PRIMARY KEY,
                               IdDemandeur INTEGER REFERENCES Utilisateur(IdUtilisateur),
                               deviseVoulu VARCHAR(3) REFERENCES Devise(CodeDevise),
                               deviseOfferte VARCHAR(3) REFERENCES Devise(CodeDevise),
                               montantVoulu NUMERIC(15, 2),
                               Statut StatutDemande,
                               DateDemande TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Création de la table OffreDevise
CREATE DOMAIN StatutOffre AS VARCHAR(255) CHECK (VALUE IN ('ENATTENTE', 'ACCEPTER', 'REFUSER', 'PAYER',
                                                           'ANNULER', 'TERMINER'));
CREATE TABLE IF NOT EXISTS OffreDevise (
                             IdOffre SERIAL PRIMARY KEY,
                             IdDemande INTEGER REFERENCES DemandeDevise(IdDemande),
                             IdOffreur INTEGER REFERENCES Utilisateur(IdUtilisateur),
                             Statut StatutOffre,
                             DateOffre TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Création de la table Transaction
-- CREATE TABLE Transaction (
--                              IdTransaction SERIAL PRIMARY KEY,
--                              IdDemande INTEGER REFERENCES DemandeDevise(IdDemande),
--                              IdOffre INTEGER REFERENCES OffreDevise(IdOffre),
--                              DateTransaction TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--                              StatutTransaction VARCHAR(255)
-- );

-- Create a table for comments
CREATE TABLE IF NOT EXISTS Commentaire (
                             IdCommentaire SERIAL PRIMARY KEY,
                             idutilisateurnoteur INTEGER REFERENCES Utilisateur(IdUtilisateur),
                             idutilisateurnote INTEGER REFERENCES Utilisateur(IdUtilisateur),
                             IdOffre INTEGER REFERENCES DemandeDevise(IdDemande),
                             IdDemande INTEGER REFERENCES OffreDevise(IdOffre),
                             Note SMALLINT,
                             TexteCommentaire TEXT,
                             CommentDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO Devise (CodeDevise, NomDevise) VALUES
                                               ('AFN',	'Afghanistan Afghani'),
                                               ('ALL',	'Albanie Lek'),
                                               ('AMD',	'Arménie Dram'),
                                               ('ANG',	'Antilles néerlandaises Florin'),
                                               ('AOA',	'Angola Kwanza'),
                                               ('ARS',	'Argentine Peso'),
                                               ('AUD',	'Dollar d’Australie'),
                                               ('AWG',	'Aruba Florin'),
                                               ('AZN',	'Azerbaïdjan Manat'),
                                               ('BAM',	'Bosnie-Herzégovine Mark convertible'),
                                               ('BBD',	'Barbade Dollar'),
                                               ('BDT',	'Bangladesh Taka'),
                                               ('BGN',	'Bulgarie Lev'),
                                               ('BHD',	'Bahreïn Dinar'),
                                               ('BIF',	'Burundi Franc'),
                                               ('BMD',	'Bermudes Dollar'),
                                               ('BND',	'Brunei Dollar'),
                                               ('BOB',	'Bolivie Bolíviano'),
                                               ('BRL',	'Brésil Réal'),
                                               ('BSD',	'Bahamas Dollar'),
                                               ('BTN',	'Bhoutan Ngultrum'),
                                               ('BWP',	'Pula Pula'),
                                               ('BYN',	'Biélorussie Rouble'),
                                               ('BZD',	'Belize Dollar'),
                                               ('CAD',	'Dollar du Canada'),
                                               ('CDF',	'République démocratique du Congo/Kinshasa Franc'),
                                               ('CHF',	'Franc de Suisse'),
                                               ('CLP',	'Chili Peso'),
                                               ('CNY',	'Yuan ou renminbi de Chine'),
                                               ('COP',	'Colombie Peso'),
                                               ('CRC',	'Costa Rica Colon'),
                                               ('CUC',	'Cuba Peso convertible'),
                                               ('CUP',	'Cuba Peso'),
                                               ('CVE',	'Cap-Vert Escudo'),
                                               ('CZK',	'République tchèque Couronne'),
                                               ('DJF',	'Djibouti Franc'),
                                               ('DKK',	'Danemark Couronne'),
                                               ('DOP',	'République dominicaine Peso'),
                                               ('DZD',	'Algérie Dinar'),
                                               ('EGP',	'Égypte Livre'),
                                               ('ERN',	'Érythrée Nakfa'),
                                               ('ETB',	'Éthiopie Birr'),
                                               ('EUR',	'États membres de la zone euro'),
                                               ('FJD',	'Fidji Dollar'),
                                               ('FKP',	'Îles Falkland (Malouines) Livre'),
                                               ('GBP',	'Livre du Royaume-Uni'),
                                               ('GEL',	'Géorgie Lari'),
                                               ('GGP',	'Guernesey Livre'),
                                               ('GHS',	'Ghana Cédi'),
                                               ('GIP',	'Gibraltar Livre'),
                                               ('GMD',	'Gambie Dalasi'),
                                               ('GNF',	'Guinée Franc'),
                                               ('GTQ',	'Guatemala Quetzal'),
                                               ('GYD',	'Guyana Dollar'),
                                               ('HKD',	'Hong Kong Dollar'),
                                               ('HNL',	'Honduras Lempira'),
                                               ('HRK',	'Croatie Kuna'),
                                               ('HTG',	'Haïti Gourde'),
                                               ('HUF',	'Hongrie Forint'),
                                               ('IDR',	'Indonésie Roupie'),
                                               ('ILS',	'Israël Shekel'),
                                               ('IMP',	'Île de Man Livre'),
                                               ('INR',	'Roupie d’Inde'),
                                               ('IQD',	'Irak Dinar'),
                                               ('IRR',	'Iran Rial'),
                                               ('ISK',	'Islande Couronne'),
                                               ('JEP',	'Jersey Livre'),
                                               ('JMD',	'Jamaïque Dollar'),
                                               ('JOD',	'Jordanie Dinar'),
                                               ('JPY',	'Yen du Japon'),
                                               ('KES',	'Kenya Shilling'),
                                               ('KGS',	'Kyrgyzstan Som'),
                                               ('KHR',	'Cambodge Riel'),
                                               ('KMF',	'Comores Franc'),
                                               ('KPW',	'Corée (du Nord) Won'),
                                               ('KRW',	'Corée (du Sud) Won'),
                                               ('KWD',	'Koweït Dinar'),
                                               ('KYD',	'Îles Caïmans Dollar'),
                                               ('KZT',	'Kazakhstan Tenge'),
                                               ('LAK',	'Laos Kip'),
                                               ('LBP',	'Liban Livre'),
                                               ('LKR',	'Sri Lanka Roupie'),
                                               ('LRD',	'Liberia Dollar'),
                                               ('LSL',	'Lesotho Loti'),
                                               ('LYD',	'Libye Dinar'),
                                               ('MAD',	'Maroc Dirham'),
                                               ('MDL',	'Moldavie Leu'),
                                               ('MGA',	'Madagascar Ariary'),
                                               ('MKD',	'Macédoine Dinar'),
                                               ('MMK',	'Myanmar (Birmanie) Kyat'),
                                               ('MNT',	'Mongolie Tugrik'),
                                               ('MOP',	'Macao Pataca'),
                                               ('MRU',	'Mauritanie Ouguiya'),
                                               ('MUR',	'Maurice Roupie'),
                                               ('MVR',	'Maldives Rufiyaa'),
                                               ('MWK',	'Malawi Kwacha'),
                                               ('MXN',	'Mexique Peso'),
                                               ('MYR',	'Ringgit de Malaisie'),
                                               ('MZN',	'Mozambique Metical'),
                                               ('NAD',	'Namibie Dollar'),
                                               ('NGN',	'Nigéria Naira'),
                                               ('NIO',	'Nicaragua Cordoba'),
                                               ('NOK',	'Norvège Couronne'),
                                               ('NPR',	'Népal Roupie'),
                                               ('NZD',	'Dollar de Nouvelle-Zélande'),
                                               ('OMR',	'Oman Rial'),
                                               ('PAB',	'Panama Balboa'),
                                               ('PEN',	'Pérou Sol'),
                                               ('PGK',	'Papouasie-Nouvelle-Guinée Kina'),
                                               ('PHP',	'Peso des Philippines'),
                                               ('PKR',	'Pakistan Roupie'),
                                               ('PLN',	'Pologne Zloty'),
                                               ('PYG',	'Paraguay Guarani'),
                                               ('QAR',	'Qatar Riyal'),
                                               ('RON',	'Roumanie Leu'),
                                               ('RSD',	'Serbie Dinar'),
                                               ('RUB',	'Russie Rouble'),
                                               ('RWF',	'Rwanda Franc'),
                                               ('SAR',	'Rial d’Arabie saoudite'),
                                               ('SBD',	'Salomon Dollar'),
                                               ('SCR',	'Seychelles Roupie'),
                                               ('SDG',	'Soudan Livre'),
                                               ('SEK',	'Suède Couronne'),
                                               ('SGD',	'Singapour Dollar'),
                                               ('SHP',	'Sainte-Hélène Pound'),
                                               ('SLL',	'Sierra Leone Leone'),
                                               ('SOS',	'Somalie Shilling'),
                                               ('SPL',	'Principauté de Seborga Luigino'),
                                               ('SRD',	'Suriname Dollar'),
                                               ('STN',	'Sao Tomé-et-Principe Dobra'),
                                               ('SVC',	'El Salvador Colon'),
                                               ('SYP',	'Syrie Livre'),
                                               ('SZL',	'Swaziland Lilangeni'),
                                               ('THB',	'Baht de Thaïlande'),
                                               ('TJS',	'Tadjikistan Somoni'),
                                               ('TMT',	'Turkménistan Manat'),
                                               ('TND',	'Tunisie Dinar'),
                                               ('TOP',	'Tonga Pa’anga'),
                                               ('TRY',	'Turquie Livre'),
                                               ('TTD',	'Trinité-et-Tobago Dollar'),
                                               ('TVD',	'Tuvalu Dollar'),
                                               ('TWD',	'Taïwan Nouveau dollar'),
                                               ('TZS',	'Tanzanie Shilling'),
                                               ('UAH',	'Ukraine Hryvnia'),
                                               ('UGX',	'Ouganda Shilling'),
                                               ('USD',	'Dollar des États-Unis'),
                                               ('UYU',	'Uruguay Peso'),
                                               ('UZS',	'Ouzbékistan Som'),
                                               ('VEF',	'Venezuela Bolivar'),
                                               ('VND',	'Viêt Nam Dong'),
                                               ('VUV',	'Vanuatu Vatu'),
                                               ('WST',	'Samoa Tala'),
                                               ('XAF',	'Franc CFA'),
                                               ('XCD',	'Caraïbes orientales Dollar'),
                                               ('XDR',	'Fonds monétaire international (FMI) Droits de tirage spéciaux'),
                                               ('XOF',	'Union économique et monétaire ouest-africaine (BCEAO) Franc'),
                                               ('XPF',	'Collectivités françaises du Pacifique (CFP) Franc'),
                                               ('YER',	'Yémen Rial'),
                                               ('ZAR',	'Rand d’Afrique du Sud'),
                                               ('ZMW',	'Zambie Kwacha'),
                                               ('ZWD',	'Zimbabwe Dollar');

-- Création de la table Devise
CREATE TABLE IF NOT EXISTS ChatRoom (
    ChatRoomId SERIAL PRIMARY KEY,
    SenderId INTEGER,
    ChatId INTEGER,
    RecepientId INTEGER
    );

-- Création de la table Devise
CREATE TABLE IF NOT EXISTS ChatMessage (
    Id SERIAL PRIMARY KEY,
    ChatId INTEGER,
    SenderId INTEGER,
    RecepientId INTEGER,
    Content VARCHAR(255),
    DateCreation TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );